### ISSUE TITLE
Library hanna code

### ISSUE THREAD

**Issue by tealborder** [BitPoet/MediaLibrary#4]
Fantastic module. Appreciate your efforts. Any chance for a hanna shortcode to display all images from one library?

This would enable multiple galleries on a single page.

**Comment by BitPoet** [comment]
That should be quite straight forward, since a library is just a page with an image field an a file field. The PHP could be something like this:
```php
$ml = wire('modules')->get('MediaLibrary');
$lib = $ml->getPageMediaLibraries($page)->findOne("name=$library");
foreach($lib->MediaImages as $img) {
    echo "<img class='your-library-class' src='{$img->url}' title='{$img->description}'/>\n";
}
```
And you would use a Hanna code like
``[[gallery library="productlibrary"]]``

You could also pass the library page directly by id and use $pages->get instead of filtering the current page's applicable libraries like I'm doing above.
```php
foreach($pages->get($lib)->MediaImages as $img) {
  // output image
}
// Use this with a hanna code like [[gallery lib="1242"]]
```

**Comment by BitPoet** [comment]
I think the question has been answered, so I'm closing this issue.
